### ISSUE TITLE
Firefox keeps searching on every key stroke

### ISSUE THREAD

**Issue by raratiru** [taniarascia/accordion#1]
Debian 11.3 features Firefox-91.7.0esr where every key stroke results in adding the letter to the search box.

Installing chromium-100.0.4896.60, however, allowed my dream come true... painlessly!

**Comment by brian-c** [comment]
That's probably controlled by the "Search for text as your start typing" preference (toward the end of the "General" tab).

**Comment by raratiru** [comment]
Indeed! Thank you!
